services:
  control_tower_service:
    build: .
    container_name: control_tower_service
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      db_control_tower_service:
        condition: service_healthy
    networks:
      - app-network

  db_control_tower_service:
    image: postgres:alpine
    container_name: db_control_tower_service
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    external: true